site_name: Livegap Charts Documentation
site_url: https://charts.livegap.com/help
theme:
  name: material
  logo: assets/images/logo.jpeg
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: black
features:
    - navigation.top            # "Back to top" button appears upon upward scrolling
    - navigation.indexes        # Allow section headers to have a page (see tech/index.md)
    - navigation.sections       # to show first level of sections expanded
    - content.tabs.link
    - search.suggest            # Search will display the likeliest completion for the last word
    - search.highlight          # Highlight all occurrences after following the link
    - content.code.copy         # Code blocks render a button to allow the user to copy a code
    - content.action.edit       # Edit icon
nav:
  - Overview:
    - index.md
  - Getting started:
    - getting-started/installing.md
    - getting-started/getting-started.md
  - Charts:
    - charts/line-chart.md
    - charts/bar-chart.md
    - charts/stacked-bar-chart.md
    - charts/horizontal-bar-chart.md
    - charts/horizontal-stacked-bar.md
    - charts/bar-line-chart.md
    - charts/radar-chart.md
    - charts/pie-area-chart.md
    - charts/polar-area-chart.md
    - charts/doughnut-chart.md
    - charts/graph-chart.md
  - faqs.md

markdown_extensions:
  - admonition
  - tables

extra_css:
  - assets/stylesheets/styles.css